package ch.ethz.mc.services.types;

/**
 * @author Andreas Filler
 */
public enum ScreeningSurveySessionAttributeTypes {
	PARTICIPANT_ID, PARTICIPANT_ACCESS_GRANTED, PARTICIPANT_FORMER_SCREENING_SURVEY_SLIDE_ID, PARTICIPANT_FEEDBACK_URL, SCREENING_SURVEY_CONSISTENCY_CHECK_VALUE, FROM_SCREENING_SURVEY
}
