package ch.ethz.mc.ui.components.main_view.interventions.variables;

/* ##LICENSE## */
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.val;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.VerticalLayout;

import ch.ethz.mc.ui.components.AbstractCustomComponent;

/**
 * Provides the intervention variables tab component
 * 
 * @author Andreas Filler
 */
@SuppressWarnings("serial")
@Data
@EqualsAndHashCode(callSuper = false)
public abstract class VariablesTabComponent extends AbstractCustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout			mainLayout;
	@AutoGenerated
	private VariablesEditComponent	variablesEditComponent;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	protected VariablesTabComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// manually added
		// table options
		val interventionVariablesTable = variablesEditComponent
				.getVariablesTable();
		interventionVariablesTable.setSelectable(true);
		interventionVariablesTable.setImmediate(true);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		// interventionVariablesEditComponent
		variablesEditComponent = new VariablesEditComponent();
		variablesEditComponent.setImmediate(false);
		variablesEditComponent.setWidth("100.0%");
		variablesEditComponent.setHeight("-1px");
		mainLayout.addComponent(variablesEditComponent);

		return mainLayout;
	}
}
