package ch.ethz.mc.ui.views.components.interventions;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.val;
import ch.ethz.mc.ui.views.components.AbstractCustomComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.VerticalLayout;

/**
 * Provides the intervention access tab component
 * 
 * @author Andreas Filler
 */
@SuppressWarnings("serial")
@Data
@EqualsAndHashCode(callSuper = false)
public abstract class InterventionAccessTabComponent extends
		AbstractCustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout					mainLayout;
	@AutoGenerated
	private InterventionAccessEditComponent	interventionAccessEditComponent;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	protected InterventionAccessTabComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// manually added
		// table options
		val accountsTable = interventionAccessEditComponent.getAccountsTable();
		accountsTable.setSelectable(true);
		accountsTable.setImmediate(true);

		// combo box options
		val accountsSelectComboBox = interventionAccessEditComponent
				.getAccountsSelectComboBox();
		accountsSelectComboBox.setTextInputAllowed(false);
		accountsSelectComboBox.setNewItemsAllowed(false);
		accountsSelectComboBox.setImmediate(true);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		// interventionAccessEditComponent
		interventionAccessEditComponent = new InterventionAccessEditComponent();
		interventionAccessEditComponent.setImmediate(false);
		interventionAccessEditComponent.setWidth("100.0%");
		interventionAccessEditComponent.setHeight("-1px");
		mainLayout.addComponent(interventionAccessEditComponent);

		return mainLayout;
	}
}
